Update update-readme.yml

diff --git a/.github/workflows/update-readme.yml b/.github/workflows/update-readme.yml
--- a/.github/workflows/update-readme.yml
+++ b/.github/workflows/update-readme.yml
@@ -10,18 +10,25 @@ jobs:
 
     steps:
     - name: Checkout repository
-      uses: actions/checkout@v3
+      uses: actions/checkout@v4
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
 
     - name: Get release version
       id: get_version
-      run: echo "KEY=version::$(echo $GITHUB_REF | sed 's/refs\/tags\///')" >>$GITHUB_OUTPUT
+      run: echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
 
     - name: Update README.md
       run: |
-        sed -i "s/v[0-9]*\.[0-9]*\.[0-9]*/v${{ steps.get_version.outputs.version }}/g" README.md
+        if ! sed -i "s/v[0-9]*\.[0-9]*\.[0-9]*/v${{ steps.get_version.outputs.version }}/g" README.md; then
+          echo "ERROR: Failed to update version in README.md"
+          exit 1
+        fi
+
         git config --global user.name 'github-actions[bot]'
         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
         git checkout master
+        git pull origin master
         git add README.md
         git commit -m "Update README version to ${{ steps.get_version.outputs.version }}."
         git push origin master
